// NativeWind zet zijn klassen om op gewone componenten, maar niet op de
// Animated-varianten van Reanimated. Alles wat van kleur verschiet is er zo een,
// dus die krijgen hier een echte stijl in plaats van een className. De maten
// komen één op één uit de webversie.
export const L = {
  titel: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 36, lineHeight: 38, letterSpacing: -0.5 },
  onder: { fontFamily: 'Nunito_700Bold', fontSize: 15, marginTop: 3 },
  groep: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 17 },
  groeptijd: { fontFamily: 'Nunito_700Bold', fontSize: 13 },
  taaknaam: { fontFamily: 'Baloo2_700Bold', textAlign: 'center' },
  naam: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 16 },
  telling: { fontFamily: 'Nunito_800ExtraBold', fontSize: 12.5 },
  knop: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 15 },
  kindnaam: { fontFamily: 'Nunito_800ExtraBold', fontSize: 11 },
  blokkop: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 16, lineHeight: 22 },
  agendanaam: { fontFamily: 'Baloo2_700Bold', fontSize: 15.5 },
  agendatijd: { fontFamily: 'Nunito_800ExtraBold', fontSize: 12.5 },
  merk: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 12.5 },
  tab: { fontFamily: 'Nunito_800ExtraBold', fontSize: 10.5 },
  tabbreed: { fontFamily: 'Nunito_800ExtraBold', fontSize: 13.5 },
  wletter: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 12 },
  wdag: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 17 },
  kaartknop: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 15.5 },
  lijsttitel: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 16 },
  lijstuitleg: { fontFamily: 'Nunito_700Bold', fontSize: 12.5, marginTop: 1 },
  leeg: { fontFamily: 'Nunito_700Bold', fontSize: 16, textAlign: 'center' },
  voetnoot: { fontFamily: 'Nunito_700Bold', fontSize: 12, textAlign: 'center', marginTop: 20 },
  formkop: { fontFamily: 'Nunito_800ExtraBold', fontSize: 11.5, letterSpacing: 0.6,
             paddingHorizontal: 6, paddingBottom: 8 },
  notitie: { fontFamily: 'Nunito_700Bold', fontSize: 12.5, lineHeight: 17,
             paddingTop: 10, paddingHorizontal: 8 },
  melding: { fontFamily: 'Nunito_700Bold', fontSize: 13 },
  chip: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 14 },
  toevoeg: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 15.5 },
  rijlabel: { fontFamily: 'Baloo2_700Bold', fontSize: 15.5 },
  rijdagen: { fontFamily: 'Nunito_800ExtraBold', fontSize: 11.5, letterSpacing: 0.2 },
  bladkop: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 18, textAlign: 'center' },
  tekstknop: { fontFamily: 'Nunito_800ExtraBold', fontSize: 16, color: '#F2994A' },
  grootknop: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 16 },
  opnieuw: { fontFamily: 'Nunito_800ExtraBold', fontSize: 13 },
  bezig: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 16, lineHeight: 22,
           textAlign: 'center', paddingVertical: 34, paddingHorizontal: 12 },
  vraagnaam: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 15.5 },
  vondstnaam: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 15.5 },
  vondstmeta: { fontFamily: 'Nunito_800ExtraBold', fontSize: 12.5, paddingTop: 2 },
  vondstbron: { fontFamily: 'Nunito_700Bold', fontSize: 12, fontStyle: 'italic',
                lineHeight: 16, paddingTop: 5, opacity: 0.85 },
} as const;
